# Generated by Django 4.0.5 on 2022-09-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('std', models.IntegerField()),
                ('sub1_mark', models.IntegerField()),
                ('sub2_mark', models.IntegerField()),
                ('sub3_mark', models.IntegerField()),
                ('sub4_mark', models.IntegerField()),
                ('sub5_mark', models.IntegerField()),
                ('Rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('phoneno', models.IntegerField(max_length=11)),
            ],
        ),
    ]
